app/urls.py
from django.conf.urls import url

from app.views import HomeView, onewire_ajax, DomesticWaterView, ModbusServerView, sheme_ajax, \
    MainView, StatusView, HeatingCircuitView, HeatingZoneView, HeatingBoilerView, ModbusDeviceView, progress_bar, \
    OutdoorSensorView

urlpatterns = [
    url(r'^hardware/$', HomeView.as_view(), name='home'),
    url(r'^bin/$', onewire_ajax, name='onewire-ajax'),
    url(r'^sheme-ajax/$', sheme_ajax, name='sheme-ajax'),
    url(r'^heating-zones/$', HeatingZoneView.as_view(), name='heating-zones'),
    url(r'^domestic-water/$', DomesticWaterView.as_view(), name='domestic-water'),
    url(r'^modbus-server/$', ModbusServerView.as_view(), name='modbus-server'),
    url(r'^modbus-devices/$', ModbusDeviceView.as_view(), name='modbus-devices'),
    url(r'^outdoor-sensor/$', OutdoorSensorView.as_view(), name='outdoor-sensor'),
    url(r'^$', MainView.as_view(), name='main'),
    url(r'^status/$', StatusView.as_view(), name='status'),
    url(r'^heating-circuits/$', HeatingCircuitView.as_view(), name='heating-circuits'),
    url(r'^heating-boilers/$', HeatingBoilerView.as_view(), name='heating-boilers'),
    url(r'^progress-bar/$', progress_bar, name='progress-bar'),
]

pipcwebmod/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('app.urls', namespace='app')),
]

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Pipcwebmod</title>

    <link rel="stylesheet" href="{% static '/css/bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static '/css/styles.css' %}" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Titillium+Web" rel="stylesheet">
    {% block head %}

    {% endblock head %}

</head>
<body>
    <section>
        <nav class="navbar">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="{% url 'app:main' %}"><span><img alt="Logo" id="optiheat-logo" src="{% static '/img/optiheat-logo.png' %}"></span></a>
                </div>
                <div class="collapse navbar-collapse" id="myNavbar">
                    <ul class="nav navbar-nav">
                        <li class="{% if request.path == '/' %}active{% endif %}"><a href="{% url 'app:main' %}">Main</a></li>
                        <li class="{% if request.path == '/hardware/' %}active{% endif %}"><a href="{% url 'app:home' %}">Hardware</a></li>
                        <li class="{% if request.path == '/modbus-server/' %}active{% endif %}"><a href="{% url 'app:modbus-server' %}">Modbus Server</a></li>
                        <li class="{% if request.path == '/modbus-devices/' %}active{% endif %}"><a href="{% url 'app:modbus-devices' %}">Modbus Devices</a></li>
                        <li class="{% if request.path == '/outdoor-sensor/' %}active{% endif %}"><a href="{% url 'app:outdoor-sensor' %}">Outdoor Sensor</a></li>
                        <li class="{% if request.path == '/heating-zones/' %}active{% endif %}"><a href="{% url 'app:heating-zones' %}">Heating Zones</a></li>
                        <li class="{% if request.path == '/domestic-water/' %}active{% endif %}"><a href="{% url 'app:domestic-water' %}">Domestic Water</a></li>
                        <li class="{% if request.path == '/heating-circuits/' %}active{% endif %}"><a href="{% url 'app:heating-circuits' %}">Heating Circuits</a></li>
                        <li class="{% if request.path == '/heating-boilers/' %}active{% endif %}"><a href="{% url 'app:heating-boilers' %}">Heating Boilers</a></li>
                        <li class="{% if request.path == '/status/' %}active{% endif %}"><a href="{% url 'app:status' %}">Status</a></li>
                    </ul>
                </div>
            </div>
        </nav>
    </section>

{% block content %}

{% endblock content %}

    <script src="{% static '/js/jquery-latest.js' %}"></script>
    <script src="{% static '/js/jquery.min.js' %}"></script>
    <script src="{% static '/js/bootstrap.min.js' %}"></script>

{% block customscripts %}

{% endblock customscripts %}

</body>
</html>