app/urls.py
from django.conf.urls import url

from app.views import HomeView, onewire_ajax, DomesticWaterView, ModbusServerView, sheme_ajax, \
    MainView, StatusView, HeatingCircuitView, HeatingZoneView, HeatingBoilerView, ModbusDeviceView, progress_bar, \
    OutdoorSensorView

urlpatterns = [
    url(r'^hardware/$', HomeView.as_view(), name='home'),
    url(r'^bin/$', onewire_ajax, name='onewire-ajax'),
    url(r'^sheme-ajax/$', sheme_ajax, name='sheme-ajax'),
    url(r'^heating-zones/$', HeatingZoneView.as_view(), name='heating-zones'),
    url(r'^domestic-water/$', DomesticWaterView.as_view(), name='domestic-water'),
    url(r'^modbus-server/$', ModbusServerView.as_view(), name='modbus-server'),
    url(r'^modbus-devices/$', ModbusDeviceView.as_view(), name='modbus-devices'),
    url(r'^outdoor-sensor/$', OutdoorSensorView.as_view(), name='outdoor-sensor'),
    url(r'^$', MainView.as_view(), name='main'),
    url(r'^status/$', StatusView.as_view(), name='status'),
    url(r'^heating-circuits/$', HeatingCircuitView.as_view(), name='heating-circuits'),
    url(r'^heating-boilers/$', HeatingBoilerView.as_view(), name='heating-boilers'),
    url(r'^progress-bar/$', progress_bar, name='progress-bar'),
]

pipcwebmod/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('app.urls', namespace='app')),
]

app/templates/_lx_1.html
{% load staticfiles %}

<div id="digital_outputs" class="form-group col-lg-offset-2 col-lg-2 col-md-6 col-sm-6 col-xs-4">
    <div class="form-horizontal remove-margin" style="margin-top:75px;">
        {% for output in digital_outputs|slice:":6" %}
            <input type="text" style="max-width: 331px;" class="form-control input-sm pull-right"
                   name="DO{{ forloop.counter0 }}" placeholder="DO{{ forloop.counter0 }}"
                   value="{{ output }}">
        {% endfor %}
    </div>
    <div class="form-horizontal pull-right remove-margin" style="margin-top:30px;">
        {% for output in digital_outputs|slice:"6:12" %}
            <input type="text" style="max-width: 331px;" class="form-control input-sm pull-right"
                   name="DO{{ forloop.counter0|add:6 }}"
                   placeholder="DO{{ forloop.counter0|add:6 }}" value="{{ output }}">
        {% endfor %}
    </div>
</div>
<div class="col-lg-4 hidden-md hidden-sm hidden-xs">
    <img src="{% static 'img/lx_1_2.png' %}" class="img-responsive text-center" style="margin: 0 auto;min-width: 417px;">
</div>
<div class="col-lg-4 col-md-6 col-sm-6 col-xs-8">
    <div id="analog_inputs" class="form-group remove-margin" style="margin-top:110px;">
        {% for input in analog_inputs %}
            <div class="form-inline">
                <div class="form-group">
                    <input type="text" class="form-control input-sm"
                           name="AI{{ forloop.counter0 }}"
                           placeholder="AI{{ forloop.counter0 }}" value="{{ input }}">
                    <select class="form-control input-sm">
                        <option value="temperature" {% if input.type == "temperature" %}selected="selected"{% endif %}>
                            Temperature
                        </option>
                        <option value="potenciometer"
                                {% if input.type == "potenciometer" %}selected="selected"{% endif %}>Potenciometer
                        </option>
                    </select>
                    <select class="form-control input-sm pt-dropdown">
                        <option value="pt100" {% if input.para_type == "pt100" %}selected="selected"{% endif %}>PT100</option>
                        <option value="pt1000" {% if input.para_type == "pt1000" %}selected="selected"{% endif %}>PT1000</option>
                        <option value="pt500" {% if input.para_type == "pt500" %}selected="selected"{% endif %}>PT500</option>
                        <option value="custom" {% if input.para_type == "custom" %}selected="selected"{% endif %}
                                custom-para="{% if input.para_type == "custom" %}{{ input.parameters }}{% else %}[{'x':0,'t':0}]{% endif %}">Custom</option>
                    </select>
                </div>
            </div>
        {% endfor %}
    </div>
    <div id="analog_outputs" class="form-group remove-margin" style="margin-top:30px;">
        <div class="form-horizontal">
            {% for output in analog_outputs %}
                <input type="text" style="max-width:331px;" class="form-control input-sm"
                       name="AO{{ forloop.counter0 }}"
                       placeholder="AO{{ forloop.counter0 }}" value="{{ output }}">
            {% endfor %}
        </div>
    </div>
    <div id="digital_inputs" class="form-group remove-margin" style="margin-top:24px;">
        <div class="form-horizontal">
            {% for input in digital_inputs %}
                <input type="text" style="max-width:331px;" class="form-control input-sm"
                       name="DI{{ forloop.counter0 }}" placeholder="DI{{ forloop.counter0 }}"
                       value="{{ input }}">
            {% endfor %}
        </div>
    </div>
</div>

app/templates/_lx_1_2.html
{% load staticfiles %}

<div id="digital_outputs" class="form-group col-lg-offset-2 col-lg-2 col-md-6 col-sm-6 col-xs-4">
    <div class="form-horizontal remove-margin" style="margin-top:75px;">
        {% for output in digital_outputs|slice:":4" %}
            <input type="text" style="max-width: 331px;" class="form-control input-sm pull-right"
                   name="DO{{ forloop.counter0 }}" placeholder="DO{{ forloop.counter0 }}"
                   value="{{ output }}">
        {% endfor %}
    </div>
    <div class="form-horizontal pull-right remove-margin" style="margin-top:60px;">
        {% for output in digital_outputs|slice:"4:" %}
            <input type="text" style="max-width: 331px;" class="form-control input-sm pull-right"
                   name="DO{{ forloop.counter0|add:4 }}"
                   placeholder="DO{{ forloop.counter0|add:4 }}" value="{{ output }}">
        {% endfor %}
    </div>
</div>
<div id="hardware_image" class="col-lg-4 hidden-md hidden-sm hidden-xs">
    <img src="{% static 'img/lx_1_2.png' %}" class="img-responsive text-center" style="margin: 0 auto;min-width: 417px;">
</div>
<div class="col-lg-4 col-md-6 col-sm-6 col-xs-8">
    <div id="analog_inputs" class="form-group remove-margin" style="margin-top:110px;">
        {% for input in analog_inputs %}
            <div class="form-inline">
                <div class="form-group">
                    <input type="text" class="form-control input-sm"
                           name="AI{{ forloop.counter0 }}"
                           placeholder="AI{{ forloop.counter0 }}" value="{{ input }}">
                    <select class="form-control input-sm">
                        <option value="temperature"
                                {% if input.type == "temperature" %}selected="selected"{% endif %}>Temperature
                        </option>
                        <option value="potenciometer"
                                {% if input.type == "potenciometer" %}selected="selected"{% endif %}>Potenciometer
                        </option>
                    </select>
                    <select class="form-control input-sm pt-dropdown">
                        <option value="pt100" {% if input.para_type == "pt100" %}selected="selected"{% endif %}>PT100</option>
                        <option value="pt1000" {% if input.para_type == "pt1000" %}selected="selected"{% endif %}>PT1000</option>
                        <option value="pt500" {% if input.para_type == "pt500" %}selected="selected"{% endif %}>PT500</option>
                        <option value="custom" {% if input.para_type == "custom" %}selected="selected"{% endif %}
                                custom-para="{% if input.para_type == "custom" %}{{ input.parameters }}{% else %}[{'x':0,'t':0}]{% endif %}">Custom</option>
                    </select>
                </div>
            </div>
        {% endfor %}
    </div>
    <div id="analog_outputs" class="form-group remove-margin" style="margin-top:30px;">
        <div class="form-horizontal">
            {% for output in analog_outputs %}
                <input type="text" style="max-width:331px;" class="form-control input-sm"
                       name="AO{{ forloop.counter0 }}"
                       placeholder="AO{{ forloop.counter0 }}" value="{{ output }}">
            {% endfor %}
        </div>
    </div>
    <div id="digital_inputs" class="form-group remove-margin" style="margin-top:24px;">
        <div class="form-horizontal">
            {% for input in digital_inputs %}
                <input type="text" style="max-width:331px;" class="form-control input-sm"
                       name="DI{{ forloop.counter0 }}" placeholder="DI{{ forloop.counter0 }}"
                       value="{{ input }}">
            {% endfor %}
        </div>
    </div>
</div>

app/templates/_rasp.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

app/templates/main.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}
    <div class="container">
        <div class="row aliceblue">
            <div class="col-md-12">
                <h3>Serial number:</h3>
                <p>{{ serial }}</p>
                <h3>Timezone settings</h3>
                <form action="" method="POST">{% csrf_token %}
                    <select name="city" onchange="this.form.submit()">
                        <option disabled selected value>Select an option</option>
                        {% for city in cities %}
                        <option name="city" value="{{ city }}" {% if city == city_selected.city or city == city_selected %}selected="selected"{% endif %}>{{ city }}</option>
                        {% endfor %}
                    </select>
                </form>
{#                {{ realtime }}#}
                <div>
                    <h3>Update Gui</h3>
                    <p>Current version: {{ current_gui }}</p>
                    {% if current_gui == latest_gui %}
                        <p {% if flag is True %}style="display:none;"{% endif %}>Gui is up-to-date.</p>{% else %}
                        <p>New version {{ latest_gui }} is available</p>{% endif %}
                    <p id="gui-message">{{ gui_message }}</p>
                    <form id="update-gui-form" action="" method="post"
                          {% if current_gui == latest_gui or flag is True %}style="display:none;"{% endif %}>{% csrf_token %}
                        <input type="submit" name="update_gui" class="btn btn-danger" type-name="gui" value="Update"/>
                    </form>
                </div>
                <div>
                    <h3>Update App</h3>
                    <p>Current version: {{ current_app }}</p>
                    {% if current_app == latest_app %}
                        <p {% if flag is True %}style="display:none;"{% endif %}>App is up-to-date.</p>{% else %}
                        <p {% if flag == True %}style="display:none;"{% endif %}>New version {{ latest_app }} is available</p>{% endif %}
                    <p id="app-message">{{ app_message }}</p>
                    <form id="update-app-form" action="" method="post"
                          {% if current_app == latest_app or flag is True %}style="display:none;"{% endif %}>{% csrf_token %}
                        <input type="submit" name="update_app" class="btn btn-danger" type-name="app" value="Update"/>
                    </form>
                </div>
                <br>
                <div class="progress" style="display:none;">
                    <div class="progress-bar progress-bar-success" role="progressbar" style="width: 0%"></div>
                </div>
                <div id="loader" style="display:none;"></div>
            </div>
        </div>
    </div>

{% endblock %}

{% block customscripts %}
    <script>
        function getCookie(name) {
            var cookieValue = null;
            if (document.cookie && document.cookie != '') {
                var cookies = document.cookie.split(';');
                for (var i = 0; i < cookies.length; i++) {
                    var cookie = jQuery.trim(cookies[i]);
                    if (cookie.substring(0, name.length + 1) == (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }

        $('a').click(function () {
            var city = $('select[name="city"]').val();
            var csrftoken = getCookie('csrftoken');
            $.ajax({
                url: '{% url 'app:main' %}',
                type: 'POST',
                data: {
                    city: city,
                    csrfmiddlewaretoken: csrftoken
                },
                dataType: 'json',
                complete: function (data) {
                    //debugMsg(data);
                },
                success: function (data) {
                    console.log(data.message)
                }
            });
        });

        function updatePost(type) {
            var csrftoken = getCookie('csrftoken');
            var hardware_type = "{{ hardware_type }}";
            var timer = 20000;
            if (hardware_type == "lx_1" && type == "gui") {
                timer = 140000
            } else if (hardware_type == "lx_1" && type == "app") {
                timer = 25000
            } else if (hardware_type != "1x_1" && type == "gui") {
                timer = 30000
            } else if (hardware_type != "1x_1" && type == "app") {
                timer = 16000
            }
            $('#loader').show();
            setTimeout(function () {
                $("body").find("select").removeAttr("disabled");
                $("body").find("a").unbind("click");
                $("input").prop('disabled', false);
                location.reload();
            }, timer);

            $.ajax({
                url: '{% url 'app:main' %}',
                type: 'POST',
                data: {
                    update: type,
                    csrfmiddlewaretoken: csrftoken
                },
                dataType: 'json',
                complete: function (data) {
                    //debugMsg(data);
                },
                success: function (data) {

                }
            });
        }

        function get_progress(type, mark) {
            var csrftoken = getCookie('csrftoken');
            $.ajax({
                url: '{% url 'app:progress-bar' %}',
                type: 'POST',
                data: {
                    update: type,
                    mark: mark,
                    csrfmiddlewaretoken: csrftoken
                },
                success: function(data) {
                    if (data.value < 100) {
                        $('.progress-bar').css('width', data.value + '%');
                        setTimeout(function () {
                            get_progress(type, "second");
                        }, 1000);
                    } else if (data.value == 100) {
                        $('.progress-bar').css('width', data.value + '%');
                        updatePost(type)
                    } else if (data.value == 999) {
                        console.log("ERROR");
                        location.reload();
                    }
                },
                complete: function() {
                }
            });
        };

        function get_status(type) {
             var csrftoken = getCookie('csrftoken');
            $.ajax({
                url: '{% url 'app:progress-bar' %}',
                type: 'POST',
                data: {
                    update: type,
                    mark: "first",
                    csrfmiddlewaretoken: csrftoken
                },
                success: function(data) {
                    if (data.value == 999) {
                        location.reload();
                    }
                },
            });
        }

        $('input[name^="update"]').click(function (e) {
            e.preventDefault();
            var type = $(this).attr('type-name');
            $(this).closest('form').hide();
            $('.progress').show();
            $("body").find("select").attr("disabled", "disabled");
            $("body").find("a").click(function (e) {
                e.preventDefault();
            });
            $("input").prop('disabled', true);
            get_status(type);
            get_progress(type, "second");
        });

    </script>
{% endblock %}

app/templates/outdoor_sensor.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}
    <div class="container">
        <div class="row aliceblue">
            <div class="col-md-12">
                <div class="col-lg-4 col-sm-4">
                    {% if not outdoor_sensor %}
                    <div>
                        <h3>Outdoor Sensor</h3>
                        <select class="outdoor-sensor-select form-control">
                            <option value="-1" table-name="undefined">No Sensor</option>
                            {% for sen in all_sensors %}
                                <option value="{{ sen.id }}" table-name="{{ sen.get_model_name }}">{{ sen.name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="margin-top20">
                        <h3>Enable Remote</h3>
                        <input type="checkbox" name="enable_remote">
                    </div>
                    <div id="data-expiration" class="margin-top20" style="display: none;">
                        <h3>Data Expiration <span><small>(hours)</small></span></h3>
                        <input type="number" min="1" max="10" name="data-expiration" class="form-control">
                    </div>
                    <div id="preferred-data" class="margin-top20" style="display: none;">
                        <h3>Preferred Data</h3>
                        <select class="preferred-data-select form-control">
                            <option value="local">Local Sensor</option>
                            <option value="remote">Remote Sensor</option>
                        </select>
                    </div>
                    <div class="margin-top20">
                        <button id="save-outdoor-sensor" type="submit" class="btn btn-default">Save</button>
                    </div>
                    {% else %}
                        {% for sensor in outdoor_sensor %}
                            <div>
                                <h3>Outdoor Sensor</h3>
                                <select class="outdoor-sensor-select form-control">
                                    <option value="-1" table-name="undefined">No Sensor</option>
                                    {% for sen in all_sensors %}
                                        <option value="{{ sen.id }}" table-name="{{ sen.get_model_name }}" {% if sensor.sensor_id == sen.id and sensor.table_name == sen.get_model_name %}selected="selected"{% endif %}>{{ sen.name }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="margin-top20">
                                <h3>Enable Remote</h3>
                                <input type="checkbox" name="enable_remote" {% if sensor.enable_remote == True %}checked="checked"{% endif %}>
                            </div>
                            <div id="data-expiration" class="margin-top20" style="display: none;">
                                <h3>Data Expiration <span><small>(hours)</small></span></h3>
                                <input type="number" min="1" max="10" name="data-expiration" class="form-control"
                                       {% if sensor.data_expire > 0 %}value="{{ sensor.data_expire }}{% endif %}">
                            </div>
                            <div id="preferred-data" class="margin-top20" style="display: none;">
                                <h3>Preferred Data</h3>
                                <select class="preferred-data-select form-control">
                                    <option value="local" {% if sensor.preffered_data == "local" %}selected="selected"{% endif %}>Local Sensor</option>
                                    <option value="remote" {% if sensor.preffered_data == "remote" %}selected="selected"{% endif %}>Remote Sensor</option>
                                </select>
                            </div>
                            <div class="margin-top20">
                                <button id="save-outdoor-sensor" type="submit" class="btn btn-default">Save</button>
                            </div>
                        {% endfor %}
                    {% endif %}
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block customscripts %}
    <script>
        function getCookie(name) {
            var cookieValue = null;
            if (document.cookie && document.cookie != '') {
                var cookies = document.cookie.split(';');
                for (var i = 0; i < cookies.length; i++) {
                    var cookie = jQuery.trim(cookies[i]);
                    if (cookie.substring(0, name.length + 1) == (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }

        jQuery(function () {
            $('input[name="enable_remote"]').change();
            $('select.outdoor-sensor-select').change();
        });

        $('input[name="enable_remote"]').change(function () {
            var sensor_id = $('.outdoor-sensor-select').val();
            if (this.checked == true && sensor_id == -1) {
                $('#data-expiration').show();
            } else if (this.checked == true && sensor_id != -1) {
                $('#data-expiration').show();
                $('#preferred-data').show();
            } else if (this.checked == false) {
                $('#data-expiration').hide();
                $('#preferred-data').hide();
            }
        });

        $('select.outdoor-sensor-select').change(function () {
            var sensor_id = $(this).val();
            var enable_remote = $('input[name="enable_remote"]').is(":checked");
            if (sensor_id == -1) {
{#                %('option[value="remote"]').prop('selected', true);#}
                $('#preferred-data').hide();
            } else if (sensor_id != -1 && enable_remote == true) {
                $('#preferred-data').show();
            }
        });

        function saveOutdoorSensor(options) {
            var csrftoken = getCookie('csrftoken');
            var sensor_id = $('.outdoor-sensor-select').val();
            var table_name = $('.outdoor-sensor-select').children(':selected').attr('table-name');
            var enable_remote = $('input[name="enable_remote"]').is(":checked");
            var data_expiration = $('input[name="data-expiration"]').val();
            var preferred_data = $('select.preferred-data-select').val();

            $.ajax({
                url: '{% url 'app:outdoor-sensor' %}',
                type: 'POST',
                data: {
                    sensor_id: sensor_id,
                    table_name: table_name,
                    enable_remote: enable_remote,
                    data_expiration: data_expiration,
                    preferred_data: preferred_data,
                    csrfmiddlewaretoken: csrftoken
                },
                dataType: 'json',
                complete: function (data) {
                    //debugMsg(data);
                },
                success: function (data) {
                    if (options && options.onSuccess) {
                        options.onSuccess();
                    }
                },
            });
        }

        $('#save-outdoor-sensor').click(function () {
            saveOutdoorSensor({onSuccess:location.reload()})
        });

    </script>

{% endblock %}

app/templates/status.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h3>Controller running: <span id="controller_status" {% if controller_status == True %}class="glyphicon glyphicon-ok"
                                              {% else %}class="glyphicon glyphicon-remove">{% endif %}</span></h3>
                <form action="" method="POST">{% csrf_token %}
                    <input type="submit" name="controller" {% if controller_status == True %}value="stop" class="btn btn-danger"
                           {% else %}value="start" class="btn btn-success"{% endif %}>
                </form>
                <h3>Watchdog running: <span id="watchdog_status" {% if watchdog_status == True %}class="glyphicon glyphicon-ok"
                                              {% else %}class="glyphicon glyphicon-remove">{% endif %}</span></h3>
                <form action="" method="POST">{% csrf_token %}
                    <input type="submit" name="watchdog" {% if watchdog_status == True %}value="stop" class="btn btn-danger"
                           {% else %}value="start" class="btn btn-success"{% endif %}>
                </form>
                <h3>Broadcast running: <span id="broadcast_status" {% if broadcast_status == True %}class="glyphicon glyphicon-ok"
                                              {% else %}class="glyphicon glyphicon-remove">{% endif %}</span></h3>
                <form action="" method="POST">{% csrf_token %}
                    <input type="submit" name="broadcast" {% if broadcast_status == True %}value="stop" class="btn btn-danger"
                           {% else %}value="start" class="btn btn-success"{% endif %}>
                </form>
                <h3>Front panel running: <span id="frontpanel_status" {% if frontpanel_status == True %}class="glyphicon glyphicon-ok"
                                              {% else %}class="glyphicon glyphicon-remove">{% endif %}</span></h3>
                <h3>Status</h3>
                <pre lang="xml" id="status_xml">{{ status_xml }}</pre>
            </div>
        </div>
    </div>

{% endblock %}

{% block customscripts %}
<script>
        function getCookie(name) {
            var cookieValue = null;
            if (document.cookie && document.cookie != '') {
                var cookies = document.cookie.split(';');
                for (var i = 0; i < cookies.length; i++) {
                    var cookie = jQuery.trim(cookies[i]);
                    if (cookie.substring(0, name.length + 1) == (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }

        (function worker() {
            var csrftoken = getCookie('csrftoken');
            $.ajax({
                url: '{% url 'app:status' %}',
                type: 'POST',
                data: {
                    status_request: "status",
                    csrfmiddlewaretoken: csrftoken,
                },
                success: function(data) {
                    if (data.controller_status == false) {
                        $('#controller_status').removeClass('glyphicon-ok').addClass('glyphicon-remove');
                        $('input[name="controller"]').removeClass('btn-danger').addClass('btn-success').val('start');
                    } else if (data.controller_status == true) {
                        $('#controller_status').removeClass('glyphicon-remove').addClass('glyphicon-ok');
                        $('input[name="controller"]').removeClass('btn-success').addClass('btn-danger').val('stop');
                    }
                    if (data.watchdog_status == false) {
                        $('#watchdog_status').removeClass('glyphicon-ok').addClass('glyphicon-remove');
                        $('input[name="watchdog"]').removeClass('btn-danger').addClass('btn-success').val('start');
                    } else if (data.watchdog_status == true) {
                        $('#watchdog_status').removeClass('glyphicon-remove').addClass('glyphicon-ok');
                        $('input[name="watchdog"]').removeClass('btn-success').addClass('btn-danger').val('stop');
                    }
                    if (data.broadcast_status == false) {
                        $('#broadcast_status').removeClass('glyphicon-ok').addClass('glyphicon-remove');
                        $('input[name="broadcast"]').removeClass('btn-danger').addClass('btn-success').val('start');
                    } else if (data.broadcast_status == true) {
                        $('#broadcast_status').removeClass('glyphicon-remove').addClass('glyphicon-ok');
                        $('input[name="broadcast"]').removeClass('btn-success').addClass('btn-danger').val('stop');
                    }
                },
                complete: function() {
                    setTimeout(worker, 3000);
                }
            });
        })();

        (function worker_xml() {
            var csrftoken = getCookie('csrftoken');
            $.ajax({
                url: '{% url 'app:status' %}',
                type: 'POST',
                data: {
                    status_xml: "status_xml",
                    csrfmiddlewaretoken: csrftoken,
                },
                success: function(data) {
                    $('#status_xml').text(data);
                },
                complete: function() {
                    setTimeout(worker_xml, 5000);
                }
            });
        })();
</script>
{% endblock %}